# .railway.yaml
name: toko-apparel  # Ganti dengan nama proyek Anda

# Konfigurasi deployment
build:
  # Jalankan perintah build sebelum aplikasi dijalankan
  command: |
    # 1. Hapus file cache lama (opsional, tapi direkomendasikan)
    rm -rf vendor bootstrap/cache/* storage/logs/* storage/framework/cache/*
    
    # 2. Instal dependency PHP
    composer install --no-interaction --optimize-autoloader --no-dev
    
    # 3. Siapkan file .env
    cp .env.example .env
    php artisan key:generate --force
    
    # 4. Jalankan migrasi database
    php artisan migrate --force
    
    # 5. Optimasi aplikasi
    php artisan optimize:clear
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    
    # 6. Buat symbolic link untuk storage (jika perlu)
    php artisan storage:link
    
    # 7. Pastikan folder storage writable
    chmod -R 775 storage bootstrap/cache

  # Perintah untuk menjalankan aplikasi (PENTING!)
  start: php -S 0.0.0.0:$PORT -t public

# Konfigurasi environment variables (opsional, bisa diatur via dashboard Railway)
environment:
  # Contoh: aktifkan debug mode sementara untuk troubleshooting
  # APP_DEBUG: "true"
  # Hapus setelah production